// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nezhtqdzlezihwrjrhmr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5lemh0cWR6bGV6aWh3cmpyaG1yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY0OTkwMTEsImV4cCI6MjA1MjA3NTAxMX0.rUXB5KpsUksNB-8Mtf2aauVmZ2QMz8cTCksN8naVal0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);